# Generated by Django 5.0.2 on 2024-04-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0002_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
